# Generated by Django 4.1 on 2022-10-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_masdatosusuario_descripcion_masdatosusuario_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masdatosusuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
