# Generated by Django 4.1 on 2022-10-01 23:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('estilo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='img_obras/')),
                ('artista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Galeria.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Avaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Galeria.obra')),
            ],
        ),
    ]
