# Generated by Django 4.1 on 2022-09-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='estilo',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='avaluador',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='obra',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
