# Generated by Django 4.1 on 2022-09-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0002_alter_artista_estilo_alter_artista_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaluador',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Galeria.obra'),
        ),
        migrations.AddField(
            model_name='obra',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Galeria.artista'),
        ),
    ]
