# Generated by Django 4.1 on 2022-09-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0003_avaluador_obra_obra_artista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaluador',
            name='obra',
        ),
    ]
